### ISSUE TITLE
No compiled guide at "here" link

### ISSUE THREAD

**Issue by Kenkleinman** [CeresBarros/SpaDES4Dummies#13]
I clicked the "here" at

The guide can be accessed [here](https://htmlpreview.github.io/?https://github.com/CeresBarros/SpaDES4Dummies/blob/development/_book/index.html),

on the readme page and got a 404 error.

**Comment by achubaty** [comment]
fixed - thanks!

https://htmlpreview.github.io/?https://github.com/CeresBarros/SpaDES4Dummies/blob/development/docs/index.html

**Comment by Kenkleinman** [comment]
Out of curiosity, is there a fix for the RandomFields issue in the simple example?  I'm new to this area (and don't expect to use spatial stuff any time soon) but it looks like using NLRM would not be an easy replacement.

**Comment by achubaty** [comment]
yes -- the most recent version of SpaDES.core uses NLMR instead of RandomFields.

(RandomFields can still technically be installed from the CRAN archive if needed)

**Comment by Kenkleinman** [comment]
When I try to compile the spades4dummies locally, it generates an error, even if I have RandomFields installed, though.
