### ISSUE TITLE
gaussMap() is defunct; use NLMR::nlm_mpd()

### ISSUE THREAD

**Issue by achubaty** [CeresBarros/SpaDES4Dummies#15]
> When I try to compile the spades4dummies locally, it generates an error, even if I have RandomFields installed, though.

_Originally posted by @Kenkleinman in https://github.com/CeresBarros/SpaDES4Dummies/issues/13#issuecomment-1241053894_

**Comment by achubaty** [comment]
@Kenkleinman

1. what are you trying to compile? Are you trying to rebuild the bookdown book, or run a specific example?
2. Can you please post the specific error(s) you are seeing, along with system information to help us diagnose the issue.

**Comment by achubaty** [comment]
@CeresBarros on my end, because we had to make defunct `SpaDES.tool::gaussMap()`, there are failures in several places:

![image](https://user-images.githubusercontent.com/3435577/189374098-0edf0ba2-a3e9-4489-916e-40408a333265.png)

In the `randomLandscapes` module I switched to using `NLMR::nlm_mpd()` in lieu of `gaussMap()`.

E.g., see https://github.com/PredictiveEcology/SpaDES.core/blob/master/inst/sampleModules/randomLandscapes/randomLandscapes.R#L112-L120

**Comment by achubaty** [comment]
@CeresBarros branch `15-use-nlmr` addresses the `gaussMap()` issue and also includes several other fixes for errors encountered during rebuilding.

1. there may be a better NLMR function to use for the maps you are trying to simulate;
2. I didn't spend any time tweaking the function call to approximate what `gaussMap()` was doing -- so the scale of the map vaules and 'chunkiness' of the landscape weren't really tweaked.

**Comment by CeresBarros** [comment]
Thanks @achubaty and @Kenkleinman for bringing up the issue. I'll have a look as soon as I can, but unlikely that'll be before next week

**Comment by CeresBarros** [comment]
fixed in current master branch
