### ISSUE TITLE
Make SpaDES 4 Dummies a general SpaDES guide/manual

### ISSUE THREAD

**Issue by CeresBarros** [CeresBarros/SpaDES4Dummies#21]
SpaDES 4 Dummies has the potential of being general guide/manual for SpaDES (like the "... For Dummies" yellow books). This may eventually _become_ a book.

Here's a first list of things to do for "transformation"

### General changes
- [ ] Part 1 and Part 2 become examples and are striped down of "SpaDES theory" - Part 1 becomes a "conventional R scripting vs SpaDES scripting" demo; Part 2 becomes a simple workflow example for statistical modelling.
- [ ] transfer repo ownership to PredictiveEcology.

### New chapters
(not necessarily in this order)
- [ ] module structure and events - metadata, inputs, outputs, scheduling 
- [ ] reproducible project setup and pkg installation - `SpaDES.project`/`Require` - and the "controller" script
- [ ] caching - operations (functions), events, whole simulation
- [ ] direct links to data and integrated data munging: `prepInputs`-family
- [ ] simple/static ecological modelling - currently Part 2 of SpaDES 4 Dummies
- [ ] complex/dynamic ecological modelling - using LandR as an example (can point to manual and provide a simple workflow (MEE paper))
- [ ] SpaDES/NetLogo vignette/chapter

@eliotmcintire / @achubaty / @tati-micheletti / @ianmseddy / @SteveCumming please add more things to the list.

**Comment by tati-micheletti** [comment]
Thanks a lot for this!! I will give it some thought. :)

**Comment by CeresBarros** [comment]
It has been decided that a general SpaDES manual will live in [https://predictiveecology.org/](https://predictiveecology.org/). A working draft exists in https://predictiveecology.org/training/_book/
