### ISSUE TITLE
clarify that `defineModule()` code is there for explanation only, not to be run directly

### ISSUE THREAD

**Issue by achubaty** [CeresBarros/SpaDES4Dummies#7]
Several users have been following this guide (great!) but are confused about how the module gets run (they are running the `defineModule()` block directly, and getting "missing object 'sim'" errors). I've been providing a canned reply to users' help requests on this:

> `defineModule()` is not intended to be run directly  by the user -- it is run internally during a `simInit()` call. In other words, you don't run a module's code directly in your session; you run `simInit()` with that module listed in the `modules` argument.

**Comment by VLucet** [comment]
Agreed, I got confused as well

**Comment by CeresBarros** [comment]
Apologies for the delay in solving this issue. This information has now bee added in the new version in two places in the _General module structure: speciesAbundance module_ section and in the _Defining the Module_ section.
see f07cab36ada519edc9cbabc53e99b52954ffb3e0
