### ISSUE TITLE
speciesTempLM module is not defined in the .rmd document.

### ISSUE THREAD

**Issue by tpgjs66** [CeresBarros/SpaDES4Dummies#9]
It seems the third module`speciesTempLM` is just a copy of the first module 'speciesAbundance'.

**Comment by VLucet** [comment]
Just came here to say I ran into the same issue. This repo is listed as one of the main resources on the SpaDES repo to learn the framework (before the vignette), and seems to be in need for an update. Its a shame because I find it well done :)

**Comment by CeresBarros** [comment]
Apologies for the delay in fixing this issue. It has now been fixed in e4fe07bfea45b7651b8779dbeaa09494d77f0901
